CREATE TABLE PLAYERS
    (ID_PLAYER INT PRIMARY KEY,
    MONEY DOUBLE);

CREATE TABLE ACTIONS
     (ID_OPERATION INT PRIMARY KEY,
     ID_PLAYER INT,
     OPERATION VARCHAR(24),
     MONEY DOUBLE,
     DATE DATE);