CREATE TABLE PLAYERS
    (ID_PLAYER INT PRIMARY KEY,
    MONEY DOUBLE);

CREATE TABLE ACTIONS
     (ID_OPERATION INT PRIMARY KEY,
     ID_PLAYER INT,
     OPERATION VARCHAR(24),
     DEBIT DOUBLE DEFAULT 0,
     CREDIT DOUBLE DEFAULT 0,
     DATE DATE);