CREATE TABLE PLAYERS
    (ID_PLAYER INT PRIMARY KEY,
    MONEY DOUBLE);

CREATE TABLE ACTIONS
     (ID_OPERATION INT NOT NULL PRIMARY KEY
      GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
     ID_PLAYER INT,
     OPERATION VARCHAR(24),
     DEBIT DOUBLE DEFAULT 0,
     CREDIT DOUBLE DEFAULT 0,
     DATE DATE);